import { CreateVehicleCategoryDto } from './dto';

const keiExciseRate = 3000;
const compactExciseRate = 4500;
const hybridLuxuryThreshold = 5500000;
const petrolLuxuryThreshold = 5000000;

export const COMMON_VEHICLE_CATEGORIES: CreateVehicleCategoryDto[] = [
  {
    code: 'MH95S',
    meaning: 'Wagon R Hybrid NA model',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['Hybrid FX-S', 'Hybrid ZX'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    notes: 'Current Wagon R mild-hybrid naturally aspirated model code.',
    sourceRefs: ['Goo-net Wagon R catalog', 'Car From Japan 2023 Wagon R MH95S listing'],
    active: true,
  },
  {
    code: 'MH85S',
    meaning: 'Wagon R non-hybrid / earlier variant',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['FX'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    notes: 'Current Wagon R non-hybrid model code.',
    sourceRefs: ['Goo-net Wagon R catalog'],
    active: true,
  },
  {
    code: 'MH55S',
    meaning: 'Older hybrid Wagon R',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['Hybrid FZ', 'Hybrid FX'],
    yearFrom: 2023,
    yearTo: 2024,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.8,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    notes: 'Older hybrid Wagon R code still seen in Sri Lankan import enquiries.',
    active: true,
  },
  {
    code: 'MH35S',
    meaning: 'Older non-hybrid Wagon R',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['FA', 'FX'],
    yearFrom: 2023,
    yearTo: 2024,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.8,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'MH34S',
    meaning: 'Previous generation Wagon R petrol',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['FX', 'FA'],
    yearFrom: 2023,
    yearTo: 2024,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.75,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'MH44S',
    meaning: 'Previous generation Wagon R hybrid',
    maker: 'Suzuki',
    model: 'Wagon R',
    grades: ['FZ', 'Stingray'],
    yearFrom: 2023,
    yearTo: 2024,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.75,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'MK94S',
    meaning: 'Spacia / Spacia Custom hybrid',
    maker: 'Suzuki',
    model: 'Spacia',
    grades: ['Hybrid G', 'Hybrid X', 'Custom Hybrid GS', 'Custom Hybrid XS', 'Spacia Gear Hybrid XZ'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    notes: 'Current Spacia family hybrid code used on 2023 onward models.',
    sourceRefs: ['Goo-net Spacia catalog', 'Goo-net Spacia Custom catalog'],
    active: true,
  },
  {
    code: 'MK54S',
    meaning: 'Spacia / Spacia Gear turbo or variant',
    maker: 'Suzuki',
    model: 'Spacia',
    grades: ['Custom Hybrid XS Turbo', 'Spacia Gear Hybrid XZ Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol Turbo',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    sourceRefs: ['Goo-net Spacia catalog', 'As Inter Japan 2024 Spacia Gear listings'],
    active: true,
  },
  {
    code: 'MK53S',
    meaning: 'Previous Spacia hybrid family',
    maker: 'Suzuki',
    model: 'Spacia',
    grades: ['Hybrid G', 'Hybrid X', 'Custom Hybrid GS', 'Custom Hybrid XS'],
    yearFrom: 2023,
    yearTo: 2024,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.8,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'HA37S',
    meaning: 'Alto petrol',
    maker: 'Suzuki',
    model: 'Alto',
    grades: ['A', 'L'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'HA97S',
    meaning: 'Alto hybrid',
    maker: 'Suzuki',
    model: 'Alto',
    grades: ['Hybrid S', 'Hybrid X'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'MR92S',
    meaning: 'Hustler hybrid NA',
    maker: 'Suzuki',
    model: 'Hustler',
    grades: ['Hybrid G', 'Hybrid X'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei crossover',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'MR52S',
    meaning: 'Hustler hybrid turbo',
    maker: 'Suzuki',
    model: 'Hustler',
    grades: ['Hybrid G Turbo', 'Hybrid X Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei crossover',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol Turbo',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 657,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'HE33S',
    meaning: 'Lapin / Alto Lapin',
    maker: 'Suzuki',
    model: 'Lapin',
    grades: ['G', 'L', 'X', 'LC'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF / 4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'LA900S',
    meaning: 'Taft 2WD',
    maker: 'Daihatsu',
    model: 'Taft',
    grades: ['X', 'G', 'G Turbo', 'Dark Chrome Venture'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei crossover',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Taft catalog', 'Car From Japan 2023 Taft LA910S listing'],
    active: true,
  },
  {
    code: 'LA910S',
    meaning: 'Taft 4WD',
    maker: 'Daihatsu',
    model: 'Taft',
    grades: ['X 4WD', 'G 4WD', 'G Turbo 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei crossover',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Taft catalog', 'Car From Japan 2023 Taft LA910S listing'],
    active: true,
  },
  {
    code: 'LA350S',
    meaning: 'Mira e:S 2WD',
    maker: 'Daihatsu',
    model: 'Mira e:S',
    grades: ['B', 'L', 'X', 'G', 'SA III'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Mira e:S catalog', 'Car From Japan 2023 Mira e:S LA350S listing'],
    active: true,
  },
  {
    code: 'LA360S',
    meaning: 'Mira e:S 4WD',
    maker: 'Daihatsu',
    model: 'Mira e:S',
    grades: ['B 4WD', 'L 4WD', 'X 4WD', 'G 4WD', 'SA III'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Mira e:S catalog'],
    active: true,
  },
  {
    code: 'LA650S',
    meaning: 'Tanto 2WD',
    maker: 'Daihatsu',
    model: 'Tanto',
    grades: ['L', 'X', 'Custom X', 'Custom RS'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'LA660S',
    meaning: 'Tanto 4WD',
    maker: 'Daihatsu',
    model: 'Tanto',
    grades: ['L 4WD', 'X 4WD', 'Custom X 4WD', 'Custom RS 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'LA850S',
    meaning: 'Move Canbus 2WD',
    maker: 'Daihatsu',
    model: 'Move Canbus',
    grades: ['Stripes G', 'Theory G', 'G Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'LA860S',
    meaning: 'Move Canbus 4WD',
    maker: 'Daihatsu',
    model: 'Move Canbus',
    grades: ['Stripes G 4WD', 'Theory G 4WD', 'G Turbo 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'S700V',
    meaning: 'Atrai / Hijet Cargo 2WD',
    maker: 'Daihatsu',
    model: 'Atrai',
    grades: ['RS', 'X', 'Deck Van', 'Hijet Cargo Cruise'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei van',
    vehicleType: 'Van',
    fuelType: 'Petrol',
    driveType: 'FR',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'S710V',
    meaning: 'Atrai / Hijet Cargo 4WD',
    maker: 'Daihatsu',
    model: 'Atrai',
    grades: ['RS 4WD', 'X 4WD', 'Deck Van 4WD', 'Hijet Cargo Cruise 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei van',
    vehicleType: 'Van',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'M900S',
    meaning: 'Thor 2WD',
    maker: 'Daihatsu',
    model: 'Thor',
    grades: ['X', 'G', 'G Turbo', 'Custom G', 'Custom G Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Mini MPV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Daihatsu Thor model information'],
    active: true,
  },
  {
    code: 'M910S',
    meaning: 'Thor 4WD',
    maker: 'Daihatsu',
    model: 'Thor',
    grades: ['X 4WD', 'G 4WD', 'Custom G 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Mini MPV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'M900A',
    meaning: 'Roomy 2WD',
    maker: 'Toyota',
    model: 'Roomy',
    grades: ['X', 'G', 'G-T', 'Custom G', 'Custom G-T'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Mini MPV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Roomy catalog', 'TCV 2023 Roomy listings'],
    active: true,
  },
  {
    code: 'M910A',
    meaning: 'Roomy 4WD',
    maker: 'Toyota',
    model: 'Roomy',
    grades: ['X 4WD', 'G 4WD', 'Custom G 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Mini MPV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Goo-net Roomy catalog'],
    active: true,
  },
  {
    code: 'A200A',
    meaning: 'Raize 1.0 turbo 2WD',
    maker: 'Toyota',
    model: 'Raize',
    grades: ['X', 'G', 'Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol Turbo',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A210A',
    meaning: 'Raize 1.0 turbo 4WD',
    maker: 'Toyota',
    model: 'Raize',
    grades: ['X 4WD', 'G 4WD', 'Z 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol Turbo',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A201A',
    meaning: 'Raize 1.2 petrol',
    maker: 'Toyota',
    model: 'Raize',
    grades: ['X', 'G', 'Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 1196,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A202A',
    meaning: 'Raize 1.2 hybrid',
    maker: 'Toyota',
    model: 'Raize',
    grades: ['Hybrid G', 'Hybrid Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF',
    transmission: 'e-Smart hybrid',
    engineCapacity: 1196,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'A200S',
    meaning: 'Rocky 1.0 turbo 2WD',
    maker: 'Daihatsu',
    model: 'Rocky',
    grades: ['L', 'X', 'Premium'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol Turbo',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A210S',
    meaning: 'Rocky 1.0 turbo 4WD',
    maker: 'Daihatsu',
    model: 'Rocky',
    grades: ['L 4WD', 'X 4WD', 'Premium 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol Turbo',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A201S',
    meaning: 'Rocky 1.2 petrol',
    maker: 'Daihatsu',
    model: 'Rocky',
    grades: ['L', 'X', 'Premium G'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 1196,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'A202S',
    meaning: 'Rocky 1.2 hybrid',
    maker: 'Daihatsu',
    model: 'Rocky',
    grades: ['Premium G HEV', 'X HEV'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF',
    transmission: 'e-Smart hybrid',
    engineCapacity: 1196,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'KSP210',
    meaning: 'Yaris 1.0 petrol',
    maker: 'Toyota',
    model: 'Yaris',
    grades: ['X', 'G'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 996,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Toyota Yaris XP210 powertrain table', 'SBI Motor 2023 Yaris KSP210 listing'],
    active: true,
  },
  {
    code: 'MXPA10',
    meaning: 'Yaris 1.5 petrol 2WD',
    maker: 'Toyota',
    model: 'Yaris',
    grades: ['X', 'G', 'Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT / Manual',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Toyota Yaris XP210 powertrain table'],
    active: true,
  },
  {
    code: 'MXPA15',
    meaning: 'Yaris 1.5 petrol 4WD',
    maker: 'Toyota',
    model: 'Yaris',
    grades: ['X 4WD', 'G 4WD', 'Z 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'MXPH10',
    meaning: 'Yaris hybrid 2WD',
    maker: 'Toyota',
    model: 'Yaris',
    grades: ['Hybrid X', 'Hybrid G', 'Hybrid Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF',
    transmission: 'eCVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    sourceRefs: ['Toyota Yaris XP210 powertrain table', 'TCV 2023 Yaris MXPH10 listings'],
    active: true,
  },
  {
    code: 'MXPH15',
    meaning: 'Yaris hybrid E-Four',
    maker: 'Toyota',
    model: 'Yaris',
    grades: ['Hybrid X E-Four', 'Hybrid G E-Four', 'Hybrid Z E-Four'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Hatchback',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'E-Four',
    transmission: 'eCVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'MXPB10',
    meaning: 'Yaris Cross 1.5 petrol 2WD',
    maker: 'Toyota',
    model: 'Yaris Cross',
    grades: ['X', 'G', 'Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'MXPB15',
    meaning: 'Yaris Cross 1.5 petrol 4WD',
    maker: 'Toyota',
    model: 'Yaris Cross',
    grades: ['X 4WD', 'G 4WD', 'Z 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'MXPJ10',
    meaning: 'Yaris Cross hybrid 2WD',
    maker: 'Toyota',
    model: 'Yaris Cross',
    grades: ['Hybrid X', 'Hybrid G', 'Hybrid Z'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF',
    transmission: 'eCVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'MXPJ15',
    meaning: 'Yaris Cross hybrid E-Four',
    maker: 'Toyota',
    model: 'Yaris Cross',
    grades: ['Hybrid X E-Four', 'Hybrid G E-Four', 'Hybrid Z E-Four'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'E-Four',
    transmission: 'eCVT',
    engineCapacity: 1490,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'RV3',
    meaning: 'Vezel petrol 2WD',
    maker: 'Honda',
    model: 'Vezel',
    grades: ['G'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 1496,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    sourceRefs: ['Honda HR-V/Vezel RV3 RV4 RV5 RV6 generation information'],
    active: true,
  },
  {
    code: 'RV4',
    meaning: 'Vezel petrol 4WD',
    maker: 'Honda',
    model: 'Vezel',
    grades: ['G 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 1496,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'RV5',
    meaning: 'Vezel e:HEV hybrid 2WD',
    maker: 'Honda',
    model: 'Vezel',
    grades: ['e:HEV X', 'e:HEV Z', 'e:HEV Play', 'e:HEV X HuNT Package'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: 'FF',
    transmission: 'e-CVT',
    engineCapacity: 1496,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    sourceRefs: ['Honda HR-V/Vezel RV3 RV4 RV5 RV6 generation information'],
    active: true,
  },
  {
    code: 'RV6',
    meaning: 'Vezel e:HEV hybrid 4WD',
    maker: 'Honda',
    model: 'Vezel',
    grades: ['e:HEV X 4WD', 'e:HEV Z 4WD', 'e:HEV X HuNT Package 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Compact SUV',
    vehicleType: 'Car',
    fuelType: 'Hybrid Petrol',
    driveType: '4WD',
    transmission: 'e-CVT',
    engineCapacity: 1496,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: compactExciseRate,
    defaultLuxuryThresholdLkr: hybridLuxuryThreshold,
    active: true,
  },
  {
    code: 'JF5',
    meaning: 'N-BOX 2WD',
    maker: 'Honda',
    model: 'N-BOX',
    grades: ['N-BOX', 'Fashion Style', 'Custom', 'Custom Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'JF6',
    meaning: 'N-BOX 4WD',
    maker: 'Honda',
    model: 'N-BOX',
    grades: ['N-BOX 4WD', 'Custom 4WD', 'Custom Turbo 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei tall wagon',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'JH3',
    meaning: 'N-WGN 2WD',
    maker: 'Honda',
    model: 'N-WGN',
    grades: ['G', 'L', 'Custom L', 'Custom L Turbo'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'JH4',
    meaning: 'N-WGN 4WD',
    maker: 'Honda',
    model: 'N-WGN',
    grades: ['G 4WD', 'L 4WD', 'Custom L 4WD', 'Custom L Turbo 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'JG3',
    meaning: 'N-ONE 2WD',
    maker: 'Honda',
    model: 'N-ONE',
    grades: ['Original', 'Premium', 'RS'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: 'FF',
    transmission: 'CVT / 6MT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
  {
    code: 'JG4',
    meaning: 'N-ONE 4WD',
    maker: 'Honda',
    model: 'N-ONE',
    grades: ['Original 4WD', 'Premium 4WD'],
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'Kei hatchback',
    vehicleType: 'Car',
    fuelType: 'Petrol',
    driveType: '4WD',
    transmission: 'CVT',
    engineCapacity: 658,
    defaultDepreciationRate: 0.85,
    defaultExciseRatePerUnitLkr: keiExciseRate,
    defaultLuxuryThresholdLkr: petrolLuxuryThreshold,
    active: true,
  },
];
